# my global config
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "44.202.252.204:9100"

  - job_name: "jenkins"
    metrics_path: '/prometheus'
    static_configs:
      - targets:
          - "44.202.252.204:8080"

  - job_name: "blackbox"
    metrics_path: /probe
    params:
      module: ["http_2xx"]
    static_configs:
      - targets:
          - "http://prometheus.io"   # Target to probe with http.
          - "http://3.235.2.67:8080"
    relabel_configs:
      - source_labels: ["__address__"]
        target_label: "__param_target"
      - source_labels: ["__param_target"]
        target_label: "instance"
      - target_label: "__address__"
        replacement: "3.237.84.112:9115"  # The blackbox exporter's real hostname:port
